#matrix enables you to run the same job on different configurations. node-version, os are all keys you can use. the 'include' key is a reserved key. It allows us to add new standard combination and even new keys that are not specified under the matix field. 'exclude' is used to exclude some combinations

name: Matrix Deployment
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [ 12, 14, 16] #node-version is user-defined
        os: [ubuntu-latest, windows-latest] # os is user defined
        include:
          - node-version: 18
            os: ubuntu-latest
            npm: 6
        exclude: 
          - node-version: 12
            os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node Js #even though it comes with ubuntu
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies for React Project
        run: npm ci
      - name: Build Project
        run: npm run build
