#matrix enables you to run the same job on different configurations

name: Matrix Deployment
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [ 12, 14, 16] #node-version is user-defined
        os: [ubuntu-latest, windows-latest] # os is user defined
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node Js #even though it comes with ubuntu
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies for React Project
        run: npm ci
      - name: Build Project
        run: npm run build
